#pragma once

enum class EState
{
    STATE_WAIT = 0,
    STATE_RHYTHM,
    STATE_READ,
    STATE_DANCE,
    STATE_WALK,
    STATE_WAVE_HAND,
};

enum class EAnimIndex : int
{
    ANIM_NO_SOUND = 1,
    ANIM_BLINK,
    ANIM_UNAZUKI,
    ANIM_UNAZUKI_STABLE,
    ANIM_LIP = 6,
    ANIM_DANCE,
    ANIM_WALK = 9,
    ANIM_WAVE_HAND,
    ANIM_BREATH = 11,
    ANIM_THINK2,
    ANIM_LOOK_SELF1,
    ANIM_LOOK_SELF2,
    ANIM_DANCE_MINI,
    ANIM_BONYARI,
    ANIM_LOOK_AROUND,
    ANIM_ARM_SWING,
    ANIM_STLETCH1,
    ANIM_UMAUMA,
    ANIM_PEACE1,
    ANIM_SHIRATSUYU,
    ANIM_PLINZ,
    ANIM_KASHIMA,
    ANIM_HAMAKAZE,
    ANIM_ZERO_TWO_DANCE,
    ANIM_DANCE2,
};